matrix:
  include:
    - os: linux
      language: cpp
      dist: xenial
      addons:
        apt:
          packages:
            - cmake

    - os: osx
      language: cpp
      osx_image: xcode8
      addons:
        apt:
          packages:
            - curl
            - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157;
      sudo apt-get update;
      sudo apt-get install -y gcc-7 g++-7;
      export CC=gcc-7;
      export CXX=g++-7;
    fi

script:
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DWRENBIND17_BUILD_TESTS=ON .. || travis_terminate 1
  - cmake --build . || travis_terminate 1
  - ctest --verbose || travis_terminate 1

notifications:
  email:
    recipients:
    - matusnov@gmail.com
  on_success: always
  on_failure: always
