matrix:
  include:
    - os: linux
      language: cpp
      dist: xenial
      addons:
        apt:
          packages:
            - cmake
            - lcov
            - curl
            - valgrind

    - os: osx
      language: cpp
      osx_image: xcode9.4
      addons:
        apt:
          packages:
            - cmake

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157;
      sudo apt-get update;
      sudo apt-get install -y gcc-7 g++-7;
      export CC=gcc-7;
      export CXX=g++-7;
    fi

script:
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DWRENBIND17_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug .. || travis_terminate 1
  - cmake --build . || travis_terminate 1
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      valgrind --suppressions=../wren.supp ./WrenBind17_tests || travis_terminate 1
    fi
  - ctest --verbose || travis_terminate 1
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      lcov --directory . --capture --output-file coverage.info;
      lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' '*tests*' '*catch2*' '*vm*' --output-file coverage.info;
      lcov --list coverage.info;
      bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports";
    fi

notifications:
  email:
    recipients:
    - matusnov@gmail.com
  on_success: always
  on_failure: always
